services:
  postgres:
    image: postgres:17
    container_name: pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music_catalog
    ports:
      - "5432:5432"
    volumes:
      - pg17data:/var/lib/postgresql/data

volumes:
  pg17data: