services:
  - type: web
    name: music-catalog-app
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8087

      - key: SPRING_DATASOURCE_URL
        sync: false

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: music-catalog-db
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: music-catalog-db
          property: password

      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate

databases:
  - name: music-catalog-db
    plan: free
    region: oregon
    databaseName: music_catalog