spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_catalog?currentSchema=public
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
