TRUNCATE TABLE playlist_tracks, album_genres, tracks, playlists, albums, artists, genres
    RESTART IDENTITY CASCADE;

INSERT INTO genres (name) VALUES
    ('Pop'),
    ('Synthpop'),
    ('Electronic'),
    ('House'),
    ('Disco'),
    ('Indie Rock'),
    ('Alternative Rock'),
    ('Hip Hop'),
    ('R&B'),
    ('Soul'),
    ('Metal'),
    ('Grunge'),
    ('Dream Pop'),
    ('Trip Hop'),
    ('Art Rock');

INSERT INTO artists (name) VALUES
    ('The Weeknd'),
    ('Daft Punk'),
    ('Dua Lipa'),
    ('Tame Impala'),
    ('Arctic Monkeys'),
    ('Radiohead'),
    ('Kendrick Lamar'),
    ('Billie Eilish'),
    ('Lana Del Rey'),
    ('Gorillaz'),
    ('Bonobo'),
    ('M83'),
    ('Tyler, The Creator'),
    ('SZA'),
    ('Foals'),
    ('Florence + The Machine'),
    ('Metallica'),
    ('Linkin Park'),
    ('Queen'),
    ('Nirvana'),
    ('Lorde');

INSERT INTO albums (title, year, artist_id)
SELECT seed.title, seed.year, artists.id
FROM (VALUES
    ('After Hours', 2020, 'The Weeknd'),
    ('Dawn FM', 2022, 'The Weeknd'),
    ('Discovery', 2001, 'Daft Punk'),
    ('Random Access Memories', 2013, 'Daft Punk'),
    ('Future Nostalgia', 2020, 'Dua Lipa'),
    ('Currents', 2015, 'Tame Impala'),
    ('AM', 2013, 'Arctic Monkeys'),
    ('OK Computer', 1997, 'Radiohead'),
    ('To Pimp a Butterfly', 2015, 'Kendrick Lamar'),
    ('DAMN.', 2017, 'Kendrick Lamar'),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 2019, 'Billie Eilish'),
    ('Born to Die', 2012, 'Lana Del Rey'),
    ('Demon Days', 2005, 'Gorillaz'),
    ('Black Sands', 2010, 'Bonobo'),
    ('Hurry Up, We''re Dreaming', 2011, 'M83'),
    ('IGOR', 2019, 'Tyler, The Creator'),
    ('SOS', 2022, 'SZA'),
    ('What Went Down', 2015, 'Foals'),
    ('Dance Fever', 2022, 'Florence + The Machine'),
    ('Master of Puppets', 1986, 'Metallica'),
    ('Hybrid Theory', 2000, 'Linkin Park'),
    ('A Night at the Opera', 1975, 'Queen'),
    ('Nevermind', 1991, 'Nirvana'),
    ('Melodrama', 2017, 'Lorde')
) AS seed(title, year, artist_name)
JOIN artists ON artists.name = seed.artist_name;

INSERT INTO album_genres (album_id, genre_id)
SELECT albums.id, genres.id
FROM (VALUES
    ('After Hours', 'Pop'), ('After Hours', 'Synthpop'), ('After Hours', 'R&B'),
    ('Dawn FM', 'Pop'), ('Dawn FM', 'Synthpop'), ('Dawn FM', 'Electronic'),
    ('Discovery', 'Electronic'), ('Discovery', 'House'), ('Discovery', 'Disco'),
    ('Random Access Memories', 'Electronic'), ('Random Access Memories', 'Disco'), ('Random Access Memories', 'Pop'),
    ('Future Nostalgia', 'Pop'), ('Future Nostalgia', 'Disco'),
    ('Currents', 'Indie Rock'), ('Currents', 'Synthpop'),
    ('AM', 'Indie Rock'), ('AM', 'Alternative Rock'),
    ('OK Computer', 'Alternative Rock'), ('OK Computer', 'Art Rock'),
    ('To Pimp a Butterfly', 'Hip Hop'), ('To Pimp a Butterfly', 'Soul'),
    ('DAMN.', 'Hip Hop'), ('DAMN.', 'R&B'),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'Pop'), ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'Alternative Rock'),
    ('Born to Die', 'Pop'), ('Born to Die', 'Dream Pop'),
    ('Demon Days', 'Alternative Rock'), ('Demon Days', 'Hip Hop'),
    ('Black Sands', 'Electronic'), ('Black Sands', 'Trip Hop'),
    ('Hurry Up, We''re Dreaming', 'Synthpop'), ('Hurry Up, We''re Dreaming', 'Dream Pop'),
    ('IGOR', 'Hip Hop'), ('IGOR', 'Soul'),
    ('SOS', 'R&B'), ('SOS', 'Pop'),
    ('What Went Down', 'Indie Rock'), ('What Went Down', 'Alternative Rock'),
    ('Dance Fever', 'Pop'), ('Dance Fever', 'Art Rock'),
    ('Master of Puppets', 'Metal'),
    ('Hybrid Theory', 'Alternative Rock'), ('Hybrid Theory', 'Metal'),
    ('A Night at the Opera', 'Art Rock'),
    ('Nevermind', 'Grunge'), ('Nevermind', 'Alternative Rock'),
    ('Melodrama', 'Pop'), ('Melodrama', 'Synthpop')
) AS seed(album_title, genre_name)
JOIN albums ON albums.title = seed.album_title
JOIN genres ON genres.name = seed.genre_name;

INSERT INTO tracks (title, duration_sec, album_id)
SELECT seed.track_title, seed.duration_sec, albums.id
FROM (VALUES
    ('After Hours', 'Alone Again', 250),
    ('After Hours', 'Too Late', 239),
    ('After Hours', 'Hardest To Love', 211),
    ('After Hours', 'Blinding Lights', 200),
    ('After Hours', 'Save Your Tears', 215),
    ('After Hours', 'After Hours', 361),
    ('Dawn FM', 'Gasoline', 212),
    ('Dawn FM', 'How Do I Make You Love Me?', 214),
    ('Dawn FM', 'Sacrifice', 188),
    ('Dawn FM', 'Out of Time', 214),
    ('Dawn FM', 'Less Than Zero', 211),
    ('Discovery', 'One More Time', 320),
    ('Discovery', 'Digital Love', 301),
    ('Discovery', 'Harder Better Faster Stronger', 224),
    ('Discovery', 'Something About Us', 232),
    ('Discovery', 'Face to Face', 240),
    ('Random Access Memories', 'Give Life Back to Music', 275),
    ('Random Access Memories', 'Lose Yourself to Dance', 353),
    ('Random Access Memories', 'Get Lucky', 369),
    ('Random Access Memories', 'Instant Crush', 337),
    ('Random Access Memories', 'Contact', 381),
    ('Future Nostalgia', 'Future Nostalgia', 184),
    ('Future Nostalgia', 'Don''t Start Now', 183),
    ('Future Nostalgia', 'Levitating', 203),
    ('Future Nostalgia', 'Physical', 193),
    ('Future Nostalgia', 'Break My Heart', 221),
    ('Currents', 'Let It Happen', 467),
    ('Currents', 'Nangs', 108),
    ('Currents', 'The Moment', 255),
    ('Currents', 'Eventually', 318),
    ('Currents', 'The Less I Know The Better', 216),
    ('AM', 'Do I Wanna Know?', 272),
    ('AM', 'R U Mine?', 201),
    ('AM', 'Arabella', 207),
    ('AM', 'Why''d You Only Call Me When You''re High?', 161),
    ('AM', 'Knee Socks', 257),
    ('OK Computer', 'Airbag', 284),
    ('OK Computer', 'Paranoid Android', 387),
    ('OK Computer', 'Subterranean Homesick Alien', 267),
    ('OK Computer', 'Karma Police', 264),
    ('OK Computer', 'No Surprises', 229),
    ('To Pimp a Butterfly', 'Wesley''s Theory', 287),
    ('To Pimp a Butterfly', 'King Kunta', 234),
    ('To Pimp a Butterfly', 'Alright', 219),
    ('To Pimp a Butterfly', 'These Walls', 300),
    ('To Pimp a Butterfly', 'i', 321),
    ('DAMN.', 'DNA.', 185),
    ('DAMN.', 'ELEMENT.', 208),
    ('DAMN.', 'HUMBLE.', 177),
    ('DAMN.', 'LOVE.', 213),
    ('DAMN.', 'DUCKWORTH.', 248),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'bad guy', 194),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'xanny', 244),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'bury a friend', 193),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'ilomilo', 156),
    ('WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'when the party''s over', 196),
    ('Born to Die', 'Born to Die', 286),
    ('Born to Die', 'Off to the Races', 300),
    ('Born to Die', 'Blue Jeans', 209),
    ('Born to Die', 'Video Games', 282),
    ('Born to Die', 'Summertime Sadness', 265),
    ('Demon Days', 'Feel Good Inc.', 222),
    ('Demon Days', 'Kids with Guns', 225),
    ('Demon Days', 'Dirty Harry', 230),
    ('Demon Days', 'Dare', 244),
    ('Demon Days', 'El Manana', 229),
    ('Black Sands', 'Prelude', 78),
    ('Black Sands', 'Kiara', 230),
    ('Black Sands', 'Kong', 236),
    ('Black Sands', 'Eyesdown', 327),
    ('Black Sands', 'Black Sands', 375),
    ('Hurry Up, We''re Dreaming', 'Midnight City', 241),
    ('Hurry Up, We''re Dreaming', 'Reunion', 235),
    ('Hurry Up, We''re Dreaming', 'Wait', 343),
    ('Hurry Up, We''re Dreaming', 'Steve McQueen', 226),
    ('Hurry Up, We''re Dreaming', 'Outro', 247),
    ('IGOR', 'EARFQUAKE', 190),
    ('IGOR', 'I THINK', 212),
    ('IGOR', 'RUNNING OUT OF TIME', 178),
    ('IGOR', 'NEW MAGIC WAND', 195),
    ('IGOR', 'A BOY IS A GUN', 210),
    ('SOS', 'Kill Bill', 153),
    ('SOS', 'Seek & Destroy', 203),
    ('SOS', 'Low', 181),
    ('SOS', 'Snooze', 201),
    ('SOS', 'Good Days', 279),
    ('What Went Down', 'Mountain at My Gates', 244),
    ('What Went Down', 'Birch Tree', 261),
    ('What Went Down', 'Night Swimmers', 283),
    ('What Went Down', 'London Thunder', 264),
    ('What Went Down', 'A Knife in the Ocean', 412),
    ('Dance Fever', 'King', 280),
    ('Dance Fever', 'Free', 234),
    ('Dance Fever', 'Choreomania', 213),
    ('Dance Fever', 'My Love', 231),
    ('Dance Fever', 'Dream Girl Evil', 227),
    ('Master of Puppets', 'Battery', 312),
    ('Master of Puppets', 'Master of Puppets', 515),
    ('Master of Puppets', 'The Thing That Should Not Be', 397),
    ('Master of Puppets', 'Welcome Home Sanitarium', 387),
    ('Master of Puppets', 'Orion', 507),
    ('Hybrid Theory', 'Papercut', 185),
    ('Hybrid Theory', 'One Step Closer', 157),
    ('Hybrid Theory', 'Crawling', 209),
    ('Hybrid Theory', 'In the End', 216),
    ('Hybrid Theory', 'Pushing Me Away', 191),
    ('A Night at the Opera', 'Death on Two Legs', 223),
    ('A Night at the Opera', 'Lazing on a Sunday Afternoon', 67),
    ('A Night at the Opera', 'You''re My Best Friend', 172),
    ('A Night at the Opera', 'Bohemian Rhapsody', 355),
    ('A Night at the Opera', 'Love of My Life', 218),
    ('Nevermind', 'Smells Like Teen Spirit', 301),
    ('Nevermind', 'In Bloom', 255),
    ('Nevermind', 'Come As You Are', 219),
    ('Nevermind', 'Lithium', 257),
    ('Nevermind', 'Drain You', 223),
    ('Melodrama', 'Green Light', 234),
    ('Melodrama', 'Sober', 197),
    ('Melodrama', 'Homemade Dynamite', 189),
    ('Melodrama', 'The Louvre', 271),
    ('Melodrama', 'Supercut', 277)
) AS seed(album_title, track_title, duration_sec)
JOIN albums ON albums.title = seed.album_title;

INSERT INTO playlists (name) VALUES
    ('Night Drive'),
    ('Focus Flow'),
    ('Guitar Heat'),
    ('Pop Essentials'),
    ('Heavy Rotation');

INSERT INTO playlist_tracks (playlist_id, track_id)
SELECT playlists.id, tracks.id
FROM (VALUES
    ('Night Drive', 'After Hours', 'Blinding Lights'),
    ('Night Drive', 'Dawn FM', 'Less Than Zero'),
    ('Night Drive', 'Discovery', 'Digital Love'),
    ('Night Drive', 'Currents', 'Let It Happen'),
    ('Night Drive', 'Hurry Up, We''re Dreaming', 'Midnight City'),
    ('Night Drive', 'Melodrama', 'Green Light'),
    ('Focus Flow', 'Black Sands', 'Kiara'),
    ('Focus Flow', 'Black Sands', 'Kong'),
    ('Focus Flow', 'Discovery', 'Something About Us'),
    ('Focus Flow', 'Hurry Up, We''re Dreaming', 'Wait'),
    ('Focus Flow', 'SOS', 'Good Days'),
    ('Focus Flow', 'Dawn FM', 'Out of Time'),
    ('Guitar Heat', 'AM', 'Do I Wanna Know?'),
    ('Guitar Heat', 'What Went Down', 'Mountain at My Gates'),
    ('Guitar Heat', 'Nevermind', 'Smells Like Teen Spirit'),
    ('Guitar Heat', 'Master of Puppets', 'Battery'),
    ('Guitar Heat', 'Nevermind', 'In Bloom'),
    ('Guitar Heat', 'Hybrid Theory', 'Papercut'),
    ('Pop Essentials', 'Future Nostalgia', 'Don''t Start Now'),
    ('Pop Essentials', 'Future Nostalgia', 'Levitating'),
    ('Pop Essentials', 'Random Access Memories', 'Get Lucky'),
    ('Pop Essentials', 'After Hours', 'Blinding Lights'),
    ('Pop Essentials', 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?', 'bad guy'),
    ('Pop Essentials', 'Future Nostalgia', 'Future Nostalgia'),
    ('Heavy Rotation', 'DAMN.', 'HUMBLE.'),
    ('Heavy Rotation', 'SOS', 'Kill Bill'),
    ('Heavy Rotation', 'Demon Days', 'Feel Good Inc.'),
    ('Heavy Rotation', 'Currents', 'The Less I Know The Better'),
    ('Heavy Rotation', 'A Night at the Opera', 'Bohemian Rhapsody'),
    ('Heavy Rotation', 'Master of Puppets', 'Master of Puppets')
) AS seed(playlist_name, album_title, track_title)
JOIN playlists ON playlists.name = seed.playlist_name
JOIN albums ON albums.title = seed.album_title
JOIN tracks ON tracks.album_id = albums.id AND tracks.title = seed.track_title;
