ALTER TABLE IF EXISTS playlists DROP CONSTRAINT IF EXISTS fk_playlists_user;
DROP INDEX IF EXISTS idx_playlists_user_id;
ALTER TABLE IF EXISTS playlists DROP COLUMN IF EXISTS user_id;
DROP TABLE IF EXISTS users CASCADE;
